#!/usr/bin/env bash

# Check if running as normal user
[ $(id -u) == "0" ] && echo "Error: Do NOT run this script as root!" && exit 1

# If we're not formatting home partition, we don't have to install
# the following items.

echo "*****************Start $SCRIPT_UTIL_SHARE/init_user_local_dirs.sh*****************"
. $SCRIPT_UTIL_SHARE/init_user_local_dirs.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_user_local_dirs.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_pyenv.sh*****************"
. $SCRIPT_UTIL_SHARE/init_pyenv.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_pyenv.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_rbenv.sh*****************"
. $SCRIPT_UTIL_SHARE/init_rbenv.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_rbenv.sh-----------------"


# echo "*****************Start $SCRIPT_UTIL_SHARE/init_nodenv.sh*****************"
# . $SCRIPT_UTIL_SHARE/init_nodenv.sh
# echo "-----------------Done $SCRIPT_UTIL_SHARE/init_nodenv.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_n.sh*****************"
. $SCRIPT_UTIL_SHARE/init_n.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_n.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_gvm.sh*****************"
. $SCRIPT_UTIL_SHARE/init_gvm.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_gvm.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_tmux.sh*****************"
. $SCRIPT_UTIL_SHARE/init_tmux.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_tmux.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_vim.sh*****************"
. $SCRIPT_UTIL_SHARE/init_vim.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_vim.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_neovim.sh*****************"
. $SCRIPT_UTIL_SHARE/init_neovim.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_neovim.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/init_shells.sh*****************"
. $SCRIPT_UTIL_SHARE/init_shells.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/init_shells.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_SHARE/install_util_in_home.sh*****************"
. $SCRIPT_UTIL_SHARE/install_util_in_home.sh
echo "-----------------Done $SCRIPT_UTIL_SHARE/install_util_in_home.sh-----------------"


echo "*****************Start $SCRIPT_UTIL_ROOT/install_network_tools_in_home.sh*****************"
. $SCRIPT_UTIL_ROOT/install_network_tools_in_home.sh
echo "-----------------Done $SCRIPT_UTIL_ROOT/install_network_tools_in_home.sh-----------------"


# Other recommended steps
## Trackpad -> tap to click
## Trackpad -> enable dragging with drag lock
## Change 'Caps Lock' to 'Control'
## Move Dock from bottom to left
## Power options (energy saver & screen saver)
## Users & Groups -> Login Items
## Keyboard shortcuts that have conflicts with SublimeText and other softwares.

# Other optional steps
#. $SYSTEM_SCRIPT_ROOT/create_ramdisk_for_browser_cache
#. $SYSTEM_SCRIPT_ROOT/create_ramdisk_on_login.sh


echo "*****************Start $WORKSPACE_SCRIPT_ROOT/init_workspace.sh*****************"
. $WORKSPACE_SCRIPT_ROOT/init_workspace.sh
echo "-----------------Done $WORKSPACE_SCRIPT_ROOT/init_workspace.sh-----------------"


#echo "*****************Start $SCRIPT_UTIL_ROOT/change_root_password.sh*****************"
#. $SCRIPT_UTIL_ROOT/change_root_password.sh
#echo "-----------------Done $SCRIPT_UTIL_ROOT/change_root_password.sh-----------------"
