#!/usr/bin/env bash

# Ref: https://gist.github.com/rxin/5085564

if [ "$1" = "help" ]
then
  echo " "
  echo "To create a RAMDISK -> Usage: `basename $0` create NAME SIZE_IN_MB"
  echo "To delete a RAMDISK -> Usage: `basename $0` delete DISK_ID"
  echo " "
  echo "DISK_ID can be shown with 'mount'. usually /dev/disk* where * is a number"
  echo " "
  echo " "
  exit 0
fi

if [ "$1" = "create" ]
then
  echo "Create ramdisk..."
  RAMDISK_NAME=$2
  RAMDISK_SIZE_MB=$3
  RAMDISK_SECTORS=$((2048 * $RAMDISK_SIZE_MB))
  DISK_ID=$(hdiutil attach -nomount ram://$RAMDISK_SECTORS)
  echo "Disk ID is :" $DISK_ID
  diskutil erasevolume HFS+ "${RAMDISK_NAME}" ${DISK_ID}
fi

if [ "$1" = "delete" ]
then
  echo "Delete/unmount ramdisk $2"
  umount -f $2
  hdiutil detach $2
fi