#!/usr/bin/env bash

export LANGUAGE="en_US:en"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# python
USER_PIP_HOME=$HOME/.local

export PATH=$SYSTEM_SCRIPT_ROOT:$APP_SCRIPT_ROOT:$APP_SCRIPT_SHARE:$WORKSPACE_SCRIPT_ROOT:$WORKSPACE_SCRIPT_SHARE:$PATH
export PATH=$PRIVATE_SYSTEM_SCRIPT_ROOT:$PRIVATE_APP_SCRIPT_ROOT:$PRIVATE_APP_SCRIPT_SHARE:$PRIVATE_WORKSPACE_SCRIPT_ROOT:$PRIVATE_WORKSPACE_SCRIPT_SHARE:$SHARE_ROOT:$PATH
export PATH=$USER_PIP_HOME/bin:$USER_LOCAL_BIN:$LINUXBREW_HOME/bin:$PATH
