#!/usr/bin/env bash

# Check if running as root
[ $(id -u) != "0" ] && echo "Error: You must be root to run this script" && exit 1

. /home/$SUDO_USER/bedroom/script/arch/util/env_vars.sh

. $SCRIPT_UTIL_ROOT/update_bashrc_profile.sh

. $SCRIPT_UTIL_ROOT/init_archlinuxcn_repo.sh

sudo pacman -Sy

. $SCRIPT_UTIL_SHARE/init_zsh.sh

. $SCRIPT_UTIL_ROOT/install_zip_tools.sh

. $SCRIPT_UTIL_ROOT/install_shadowsocks.sh

. $SCRIPT_UTIL_ROOT/install_polipo.sh

. $SCRIPT_UTIL_ROOT/init_python.sh

. $SCRIPT_UTIL_ROOT/init_ruby.sh

. $SCRIPT_UTIL_ROOT/install_fonts.sh

. $SCRIPT_UTIL_ROOT/install_ime.sh

. $SCRIPT_UTIL_ROOT/install_git.sh

. $SCRIPT_UTIL_ROOT/install_tmux.sh

. $SCRIPT_UTIL_ROOT/install_vim.sh

. $SCRIPT_UTIL_ROOT/install_chromium.sh

. $SCRIPT_UTIL_ROOT/install_sublime_text.sh

. $SCRIPT_UTIL_ROOT/install_downloader.sh

. $SCRIPT_UTIL_ROOT/install_multi_media.sh

. $SCRIPT_UTIL_ROOT/install_image_tools.sh

. $SCRIPT_UTIL_ROOT/install_util.sh

. $SCRIPT_UTIL_ROOT/install_telegram.sh

# To resolve possible gpg key issue, reinstall archlinuxcn-keyring by
#sudo pacman -S archlinuxcn-keyring
# then refresh keys by
#sudo pacman-key --refresh-keys

# If we met problem like:
# gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: IPC connect call failed
# gpg: keyserver receive failed: No dirmngr
# we can try:
#dirmngr < /dev/null
# then refresh keys by
#sudo pacman-key --refresh-keys
