#!/usr/bin/env bash

DOCKER_HITCHHIKER_LOCAL_HOME=$WORKSPACE_SCRIPT_SHARE/docker/hitchhiker_local
DOCKER_HITCHHIKER_LOCAL_PROJECT_NAME=hitchhiker_local

cd $DOCKER_HITCHHIKER_LOCAL_HOME

docker-compose -p $DOCKER_HITCHHIKER_LOCAL_PROJECT_NAME up -d
