#!/usr/bin/env bash

echo "Usage: aria2dl <url> <additional header>"
echo "Additional header sample: --header='Referer:http://pan.baidu.com/disk/home'"

aria2c -c --dir="$USER_DOWNLOADS" -s5 -x5 --user-agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0" $2 $1
