#!/usr/bin/env bash

MINICONDA_VERSION=2
MINICONDA_PREFIX="$USER_LOCAL_APP/miniconda${MINICONDA_VERSION}"
MINICONDA_BIN_FOLDER=$MINICONDA_PREFIX/bin
MINICONDA_CONDA_EXEC=$MINICONDA_BIN_FOLDER/conda
MINICONDA_ACTIVATE_EXEC=$MINICONDA_BIN_FOLDER/activate
MINICONDA_DEACTIVATE_EXEC=$MINICONDA_BIN_FOLDER/deactivate

# python2 environment with stock python
#PYTHON_2_ENV_NAME=py2
#$MINICONDA_CONDA_EXEC create -n $PYTHON_2_ENV_NAME python
#source $MINICONDA_ACTIVATE_EXEC $PYTHON_2_ENV_NAME
#source $MINICONDA_DEACTIVATE_EXEC
