#!/usr/bin/env bash

NDENV_HOME=$HOME/.ndenv
NDENV_EXEC=$NDENV_HOME/bin/ndenv

NODE_VERSION=$1
SET_GLOBAL=$2

#NODE_DOWNLOAD_MIRROR="https://nodejs.org/dist"
NODE_DOWNLOAD_MIRROR="https://npm.taobao.org/mirrors/node"

if [[ $SYSTEM_ID = "osx" ]]; then
    export NODE_TARBALL_EXTRACT_FOLDER_NAME="node-v${NODE_VERSION}-darwin-x64"
else
    export NODE_TARBALL_EXTRACT_FOLDER_NAME="node-v${NODE_VERSION}-linux-x64"
fi

NODE_TARBALL_FILE_NAME="${NODE_TARBALL_EXTRACT_FOLDER_NAME}.tar.xz"
NODE_TARBALL_DOWNLOAD_URL="${NODE_DOWNLOAD_MIRROR}/v${NODE_VERSION}/${NODE_TARBALL_FILE_NAME}"
NODE_TARBALL_SAEV_PATH=$USER_DOWNLOADS/$NODE_TARBALL_FILE_NAME
NODE_TARGET_DIR=$NDENV_HOME/versions/$NODE_VERSION

CURRENT_DIR=$(pwd)
cd $USER_DOWNLOADS
#wget -nc $NODE_TARBALL_DOWNLOAD_URL -O $NODE_TARBALL_SAEV_PATH
curl -L -o $NODE_TARBALL_SAEV_PATH $NODE_TARBALL_DOWNLOAD_URL
mkdir -p $NODE_TARGET_DIR
tar -xf $NODE_TARBALL_FILE_NAME -C $NODE_TARGET_DIR --strip-components=1
#mv ./$NODE_TARBALL_EXTRACT_FOLDER_NAME $NODE_TARGET_DIR
#rm -f $NODE_TARBALL_FILE_NAME
cd $CURRENT_DIR

eval "$($NDENV_EXEC init -)"

if [[ $SET_GLOBAL = "true" ]]; then
    $NDENV_EXEC global $NODE_VERSION
fi

$NDENV_EXEC rehash
