#!/usr/bin/env bash

MINICONDA_3_LATEST_STABLE_VERSION=miniconda3-4.3.30
MINICONDA_2_LATEST_STABLE_VERSION=miniconda2-4.3.30

. $SCRIPT_UTIL_SHARE/pyenv_install_miniconda.sh $MINICONDA_3_LATEST_STABLE_VERSION
. $SCRIPT_UTIL_SHARE/pyenv_install_miniconda.sh $MINICONDA_2_LATEST_STABLE_VERSION
