#!/usr/bin/env bash

# Check if running as root
[ $(id -u) != "0" ] && echo "Error: You must be root to run this script" && exit 1

# There's no "apt-get -y" equivalent for OpenSUSE, so some of
# the operations below may require manual confirmation.

. $HOME/bedroom/kb/script/suse/util/env_vars.sh

. $SYSTEM_SCRIPT_ROOT/repo/chromium_pepper_flash.sh

. $SYSTEM_SCRIPT_ROOT/repo/flash_plugin.sh

. $SCRIPT_UTIL_ROOT/update_bashrc_profile.sh

sudo zypper -n refresh

. $SCRIPT_UTIL_ROOT/uninstall_kmail.sh

. $SCRIPT_UTIL_ROOT/install_git.sh

. $SCRIPT_UTIL_ROOT/install_tmux.sh

. $SCRIPT_UTIL_ROOT/install_vim.sh

. $SCRIPT_UTIL_ROOT/install_chromium.sh

. $SCRIPT_UTIL_ROOT/install_pepper_flash.sh

. $SCRIPT_UTIL_ROOT/install_flash_plugin.sh

# For IME, use YAST to install Chinese language should be enough.

. $SCRIPT_UTIL_ROOT/init_python.sh

. $SCRIPT_UTIL_ROOT/init_ruby.sh

. $SCRIPT_UTIL_ROOT/install_privoxy.sh

. $SCRIPT_UTIL_ROOT/install_zip_tools.sh

. $SCRIPT_UTIL_ROOT/install_downloader.sh

. $SCRIPT_UTIL_ROOT/install_multi_media.sh

. $SCRIPT_UTIL_ROOT/install_zsh.sh

. $SCRIPT_UTIL_ROOT/install_util.sh

. $SCRIPT_UTIL_ROOT/install_linuxbrew_denpendencies.sh

sudo zypper -n upgrade
