#!/usr/bin/env bash

. $HOME/bedroom/kb/script/ubuntu/util/env_vars.sh

CONFIG_FILE_NAME=$1

CONFIG_FILE_TARGET_FOLDER=/etc/NetworkManager/dnsmasq.d

sudo rm $CONFIG_FILE_TARGET_FOLDER/$CONFIG_FILE_NAME

sudo systemctl restart NetworkManager
